// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfilesMItic.Data;

namespace PerfilesMItic.Migrations
{
    [DbContext(typeof(PerfilesMIticContext))]
    [Migration("20210720231938_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PerfilesMItic.Models.Barrio", b =>
                {
                    b.Property<int>("IdBarrio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBarrio");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Barrio");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BarioIdBarrio")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCiudad");

                    b.HasIndex("BarioIdBarrio");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Conyuge", b =>
                {
                    b.Property<int>("IdConyuge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CedulaC")
                        .HasColumnType("int");

                    b.Property<int>("CelularC")
                        .HasColumnType("int");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("NombreC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexoC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefonoC")
                        .HasColumnType("int");

                    b.HasKey("IdConyuge");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("Conyuge");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CiudadIdCiudad")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("CiudadIdCiudad");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Familiar", b =>
                {
                    b.Property<int>("IdFamiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("NombreF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoFamiliar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFamiliar");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("Familiar");
                });

            modelBuilder.Entity("PerfilesMItic.Models.FuncionPublica", b =>
                {
                    b.Property<int>("IdFP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionPublica")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoFP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("NombreFP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFP");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("FuncionPublica");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailParticular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBarrio")
                        .HasColumnType("int");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<byte[]>("JpgImagen")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pasaporte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegConducir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TelefonoMovil")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoFuncionario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Hijo", b =>
                {
                    b.Property<int>("IdHijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimientoH")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("NombreH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cantidadHijos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHijo");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("Hijo");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPais");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Barrio", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Funcionario", null)
                        .WithMany("Barrio")
                        .HasForeignKey("FuncionarioId");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Ciudad", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Barrio", "Bario")
                        .WithMany()
                        .HasForeignKey("BarioIdBarrio");

                    b.HasOne("PerfilesMItic.Models.Funcionario", null)
                        .WithMany("Ciudad")
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Bario");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Conyuge", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Departamento", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadIdCiudad");

                    b.HasOne("PerfilesMItic.Models.Funcionario", null)
                        .WithMany("Departamento")
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Familiar", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PerfilesMItic.Models.FuncionPublica", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Hijo", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Pais", b =>
                {
                    b.HasOne("PerfilesMItic.Models.Funcionario", null)
                        .WithMany("PaisNacimiento")
                        .HasForeignKey("FuncionarioId");
                });

            modelBuilder.Entity("PerfilesMItic.Models.Funcionario", b =>
                {
                    b.Navigation("Barrio");

                    b.Navigation("Ciudad");

                    b.Navigation("Departamento");

                    b.Navigation("PaisNacimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
